# Generated by Django 4.2.11 on 2024-03-19 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('surname', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('date_release', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='id_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='zavod.employee'),
        ),
        migrations.AlterField(
            model_name='work',
            name='note',
            field=models.TextField(max_length=255),
        ),
        migrations.CreateModel(
            name='RequestJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('date_start', models.DateTimeField(auto_now_add=True)),
                ('date_finish', models.DateTimeField()),
                ('result', models.BooleanField(default=False)),
                ('id_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='zavod.client')),
                ('id_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='zavod.employee')),
                ('id_work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='zavod.work')),
            ],
        ),
    ]
