# Generated by Django 4.2.11 on 2024-03-20 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zavod', '0002_client_equipment_work_id_employee_alter_work_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestjob',
            name='id_employee',
        ),
        migrations.AlterField(
            model_name='requestjob',
            name='id_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='work',
            name='id_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='employee',
        ),
    ]
