# Generated by Django 4.2.11 on 2024-03-21 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0003_remove_requestjob_id_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestjob',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='zavod.equipment'),
        ),
    ]
