# Generated by Django 4.2.11 on 2024-03-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0004_requestjob_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='date_release',
            field=models.DateField(),
        ),
    ]
