# Generated by Django 5.0.3 on 2024-03-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0004_requestjob_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='date_release',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='work',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
