# Generated by Django 4.2.11 on 2024-04-16 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0005_alter_equipment_date_release'),
        ('zavod', '0005_alter_equipment_date_release_alter_work_duration'),
    ]

    operations = [
    ]
