# Generated by Django 4.2.11 on 2024-04-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0006_merge_20240416_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='difficult',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='garantiya',
            field=models.IntegerField(default=1),
        ),
    ]
