# Generated by Django 4.2.11 on 2024-04-16 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0007_work_difficult_work_garantiya'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='brand',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='garantiya',
            field=models.IntegerField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='model',
            field=models.CharField(default=4534, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='price',
            field=models.IntegerField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='srok_sl',
            field=models.IntegerField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
